import { Link } from "react-router-dom";

export default function Terms() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#0f0a1e",
        color: "#fff",
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      }}
    >
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "60px 24px" }}>
        {/* Header */}
        <Link
          to="/"
          style={{
            display: "flex",
            alignItems: "center",
            gap: 10,
            textDecoration: "none",
            marginBottom: 48,
          }}
        >
          <div
            style={{
              width: 36,
              height: 36,
              background: "linear-gradient(135deg, #7c3aed, #06b6d4)",
              borderRadius: 10,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: 18,
            }}
          >
            ⚡
          </div>
          <span style={{ fontSize: 18, fontWeight: 700, color: "#fff" }}>
            Repurposer<span style={{ color: "#7c3aed" }}>.ai</span>
          </span>
        </Link>

        <h1 style={{ fontSize: 36, fontWeight: 800, marginBottom: 8 }}>
          Terms of Service
        </h1>
        <p style={{ color: "rgba(255,255,255,0.4)", marginBottom: 48 }}>
          Last updated: March 2026
        </p>

        {[
          {
            title: "1. Acceptance of Terms",
            content:
              'By accessing or using userepurposer.com ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.',
          },
          {
            title: "2. Description of Service",
            content:
              "Repurposer.ai is an AI-powered content repurposing platform that transforms text and URLs into multiple content formats including LinkedIn posts, Twitter threads, newsletters, and TikTok scripts.",
          },
          {
            title: "3. User Accounts",
            content:
              "You must provide accurate information when creating an account. You are responsible for maintaining the security of your account and all activity under it. You must be at least 18 years old to use this Service.",
          },
          {
            title: "4. Credits and Payments",
            content:
              "Credits are required to generate content. Credits are non-refundable once used. Payments are processed securely through Stripe. All prices are in EUR unless otherwise stated. We reserve the right to change pricing at any time.",
          },
          {
            title: "5. Acceptable Use",
            content:
              "You agree not to use the Service to generate illegal, harmful, defamatory, or misleading content. You may not attempt to reverse engineer, scrape, or abuse the platform. We reserve the right to suspend accounts that violate these terms.",
          },
          {
            title: "6. Intellectual Property",
            content:
              "Content you input remains yours. Content generated by the AI is yours to use commercially. We retain rights to the platform, technology, and infrastructure. You grant us a limited license to process your content solely to provide the Service.",
          },
          {
            title: "7. Disclaimer of Warranties",
            content:
              'The Service is provided "as is" without warranties of any kind. We do not guarantee the accuracy, quality, or fitness of AI-generated content. Always review generated content before publishing.',
          },
          {
            title: "8. Limitation of Liability",
            content:
              "To the maximum extent permitted by law, Repurposer.ai shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.",
          },
          {
            title: "9. Changes to Terms",
            content:
              "We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms. We will notify users of significant changes via email.",
          },
          {
            title: "10. Contact",
            content:
              "For questions about these Terms, contact us at support@userepurposer.com.",
          },
        ].map((section) => (
          <div
            key={section.title}
            style={{
              marginBottom: 36,
              paddingBottom: 36,
              borderBottom: "1px solid rgba(255,255,255,0.06)",
            }}
          >
            <h2
              style={{
                fontSize: 18,
                fontWeight: 700,
                color: "#a78bfa",
                marginBottom: 12,
              }}
            >
              {section.title}
            </h2>
            <p
              style={{
                color: "rgba(255,255,255,0.65)",
                lineHeight: 1.8,
                margin: 0,
              }}
            >
              {section.content}
            </p>
          </div>
        ))}

        <div
          style={{
            marginTop: 48,
            paddingTop: 32,
            borderTop: "1px solid rgba(255,255,255,0.06)",
            display: "flex",
            gap: 24,
          }}
        >
          <Link
            to="/privacy"
            style={{ color: "#7c3aed", textDecoration: "none", fontSize: 14 }}
          >
            Privacy Policy
          </Link>
          <Link
            to="/login"
            style={{
              color: "rgba(255,255,255,0.4)",
              textDecoration: "none",
              fontSize: 14,
            }}
          >
            ← Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
